### ISSUE TITLE
npm package (v2.0.3) cancel() kills the function

### ISSUE THREAD

**Issue by nikparo** [wuct/raf-throttle#111]
In the latest version on npm (2.0.3) the cancel function does not unset the `requestId`, unlike the current `master` branch. If it is called while a raf call is queued, it effectively terminates the function permanently. Could you please publish a new version to npm?

**Comment by wuct** [comment]
Thanks for let me know! It should be released long time ago. I have just published the latest version. Let me know whether the issue still existed.

**Comment by nikparo** [comment]
Thank you. However, I ended up copying the code and extending it for our use. In particular, I added `.start()` and `.stop()` functions since I found `.cancel()` to be insufficient:
1. In some browsers `cancelAnimationFrame()` is unable to cancel callbacks pending for the current animation frame. (https://github.com/whatwg/html/issues/4359)
2. Unsubscription in other libraries (in my case redux) is not necessarily immediate and may still call the function even after their `unsubscribe` callback has been called.

I also added an `isAnimationFrame` function to check whether we are currently in an animation frame in order to call some methods immediately rather than their throttled counterparts. (Only those scheduled by raf-throttle unfortunately, I don't know whether a global check is possible.)

If you want I could open pull requests for some or all of these?

**Comment by wuct** [comment]
Oh, I did not know the `cancelAnimationFrame()` works differently in different browsers, thanks for the whatwg link! 
I would like to keep the API minimized, but I am also curious about how do you implement `.start()` and `.stop()` 😆
 Do you use a flag to check whether the registered callback should be invoked or not?

**Comment by nikparo** [comment]
Yeah, essentially it's just a flag:

```js
const later = context => () => {
  requestId = null;
  if (!stopped) {
    callback.apply(context, lastArgs);
  }
};

const throttled = function(...args) {
  lastArgs = args;
  if (requestId === null && !stopped) {
    requestId = requestAnimationFrame(later(this));
  }
};

// ...

throttled.stop = () => {
  stopped = true;
  lastArgs = undefined;
  throttled.cancel();
};

throttled.start = () => {
  stopped = false;
};
```

**Comment by wuct** [comment]
Thanks for sharing 👍 
I am going to close the issue since the code has been released. Feel free to reopen if the issue still existed.
