### ISSUE TITLE
Switch to rollup

### ISSUE THREAD

**Issue by wuct** [wuct/raf-throttle#29]
https://github.com/rollup/rollup

**Comment by QuentinRoy** [comment]
The library is a single file module with no dependencies, why do you want to use a module bundler?

**Comment by wuct** [comment]
@QuentinRoy I think you are right. I didn't know much about rollup when I created this issue.

**Comment by QuentinRoy** [comment]
Actually one reason I thought you might want to use it is if you want to include a [UMD](https://github.com/umdjs/umd) wrapper. But I suppose the library is mostly fetched through `npm` anyway, is it?

**Comment by wuct** [comment]
@QuentinRoy It has supported UMD already. See [here](https://github.com/wuct/raf-throttle/blob/master/package.json#L12).

**Comment by QuentinRoy** [comment]
Oh. Right. As a suggestion, if you put it as default main your library can be safely fetched with [unpkg](https://unpkg.com) for a usage in the browser.

**Comment by wuct** [comment]
@QuentinRoy Yes, I also did that, too. You can see the link in [README](https://github.com/wuct/raf-throttle/blob/master/README.md#cdn). However, I didn't commit the build folder into git.
